/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aat1;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class loginpp extends javax.swing.JFrame {

    /**
     * Creates new form loginpp
     */
    public loginpp() {
        initComponents();
        setSize(615, 450);
        setTitle("ventana uno");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlbase = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblcontra = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtcontra = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btningresar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlbase.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new java.awt.Color(0, 0, 153)));
        pnlbase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbltitulo.setText("PAQUEO CARNAVAL!");
        pnlbase.add(lbltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 46, -1, -1));

        lblusuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblusuario.setText("Usuario:");
        pnlbase.add(lblusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 169, -1, -1));

        lblcontra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblcontra.setText("Contraseña:");
        pnlbase.add(lblcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 209, -1, -1));
        pnlbase.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 169, 124, -1));
        pnlbase.add(txtcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 209, 124, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/per2pl.jpg"))); // NOI18N
        pnlbase.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 125, 266, 221));

        btningresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btningresar.setText("Ingresar");
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });
        pnlbase.add(btningresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        btnsalir.setText("salir!");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        pnlbase.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ff.jpg"))); // NOI18N
        pnlbase.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 390));

        getContentPane().add(pnlbase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        String nombre=txtusuario.getText();
        String pass=txtcontra.getText();
        
        if(nombre.toLowerCase().equals("admin") && pass.equals("12345")) {
           menu ventana  = new menu();
           ventana.setVisible(true);
           this.dispose();
           
           
           
           
        
            
            
            
            
            
        }
        else {
            JOptionPane.showMessageDialog(null, "el usuario y la contraseña son erroneos");
            
        }
    }//GEN-LAST:event_btningresarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginpp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginpp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginpp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginpp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginpp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btningresar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblcontra;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JPanel pnlbase;
    private javax.swing.JPasswordField txtcontra;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
