
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class tablauno extends javax.swing.JFrame {

    /**
     * Creates new form tablauno
     */
     // paso numero uno 
    DefaultTableModel tablauno;
    Object[] objetotabla = new Object[5];
    int fila=01;
    
    Personas persona = new Personas();
    
    
    
    
    
    
    
    
    public tablauno() {
        initComponents();
        setTitle("Ejemplo de tabla");
        setLocationRelativeTo(null);
        setSize(580,580);
        
        // definicion de tabla con titulo.
    tablauno=(DefaultTableModel) tbldatos.getModel();
    
    btneliminar.setEnabled(false);
    btnbuscar.setEnabled(false);
    btnmodificar.setEnabled(false);
    
    
    
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbldatos = new javax.swing.JTable();
        jpnprincipal = new javax.swing.JPanel();
        jpntitulo = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        jpndatos = new javax.swing.JPanel();
        lblnombre = new javax.swing.JLabel();
        lblapellido = new javax.swing.JLabel();
        lbldireccion = new javax.swing.JLabel();
        lbledad = new javax.swing.JLabel();
        lblcorreo = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnañadir = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnenviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(580, 580));

        tbldatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Direccion", "Edad", "Correo"
            }
        ));
        jScrollPane1.setViewportView(tbldatos);

        lbltitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbltitulo.setText("Formulario de datos!");

        javax.swing.GroupLayout jpntituloLayout = new javax.swing.GroupLayout(jpntitulo);
        jpntitulo.setLayout(jpntituloLayout);
        jpntituloLayout.setHorizontalGroup(
            jpntituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpntituloLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbltitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpntituloLayout.setVerticalGroup(
            jpntituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpntituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblnombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblnombre.setText("NOMBRE:");

        lblapellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblapellido.setText("APELLIDO:");

        lbldireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbldireccion.setText("DIRECCION:");

        lbledad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbledad.setText("EDAD:");

        lblcorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblcorreo.setText("CORREO:");

        txtnombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtapellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtdireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtedad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtcorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jpndatosLayout = new javax.swing.GroupLayout(jpndatos);
        jpndatos.setLayout(jpndatosLayout);
        jpndatosLayout.setHorizontalGroup(
            jpndatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpndatosLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jpndatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpndatosLayout.createSequentialGroup()
                        .addGroup(jpndatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnombre)
                            .addComponent(lblapellido))
                        .addGap(27, 27, 27)
                        .addGroup(jpndatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(txtapellido)))
                    .addGroup(jpndatosLayout.createSequentialGroup()
                        .addGroup(jpndatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbldireccion)
                            .addComponent(lbledad)
                            .addComponent(lblcorreo))
                        .addGap(18, 18, 18)
                        .addGroup(jpndatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txtedad)
                            .addComponent(txtcorreo))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jpndatosLayout.setVerticalGroup(
            jpndatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpndatosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpndatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpndatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblapellido)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpndatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldireccion)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpndatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbledad)
                    .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpndatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcorreo)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnprincipalLayout = new javax.swing.GroupLayout(jpnprincipal);
        jpnprincipal.setLayout(jpnprincipalLayout);
        jpnprincipalLayout.setHorizontalGroup(
            jpnprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnprincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpndatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnprincipalLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jpntitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnprincipalLayout.setVerticalGroup(
            jpnprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnprincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpntitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpndatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnañadir.setText("AÑADIR");
        btnañadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnañadirActionPerformed(evt);
            }
        });

        btnmodificar.setText("MODIFICAR");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnbuscar.setText("BUSCAR");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbuscar)
                    .addComponent(btneliminar)
                    .addComponent(btnmodificar)
                    .addComponent(btnañadir))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnañadir)
                .addGap(18, 18, 18)
                .addComponent(btnmodificar)
                .addGap(26, 26, 26)
                .addComponent(btneliminar)
                .addGap(23, 23, 23)
                .addComponent(btnbuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnenviar.setText("ENVIAR DATOS");
        btnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(btnenviar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpnprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnenviar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limpiar() {
        txtnombre.setText("");
        txtapellido.setText("");
        txtdireccion.setText("");
        txtedad.setText("");
        txtcorreo.setText("");
        
    }
    
    
    
    
    private void btnañadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnañadirActionPerformed
       
        persona.setNombre(txtnombre.getText());
        persona.setApellido(txtapellido.getText());
        persona.setDireccion(txtdireccion.getText());
        persona.setEdad(txtedad.getText());
        persona.setCorreo(txtcorreo.getText());
        
        
       objetotabla[0]=txtnombre.getText();
       objetotabla[1]=txtapellido.getText();
       objetotabla[2]=txtdireccion.getText();
       objetotabla[3]=txtedad.getText();
       objetotabla[4]=txtcorreo.getText();
       tablauno.addRow(objetotabla);
       
       limpiar();
        btneliminar.setEnabled(true);
    btnbuscar.setEnabled(true);
    btnmodificar.setEnabled(true);
    
       
       
       
    }//GEN-LAST:event_btnañadirActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if(tbldatos.getSelectedRow() !=-1) {
            tablauno.removeRow(tbldatos.getSelectedRow());
            JOptionPane.showMessageDialog(null,"Se elimino el elemento" );
        }else{
            JOptionPane.showMessageDialog(null, "No hay ninguno seleccionado");
            
            
   
            
            
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        fila=tbldatos.getSelectedRow();
        if(tbldatos.getSelectedRow() !=-1) {
            
            persona.setNombre(tbldatos.getValueAt(fila, 0).toString());
            persona.setApellido(tbldatos.getValueAt(fila, 1).toString());
            persona.setDireccion(tbldatos.getValueAt(fila, 3).toString());
            persona.setCorreo(tbldatos.getValueAt(fila, 4).toString());
            
            
            
            txtnombre.setText(tbldatos.getValueAt(fila, 0).toString());
            txtapellido.setText(tbldatos.getValueAt(fila, 1).toString());
            txtdireccion.setText(tbldatos.getValueAt(fila, 2).toString());
            txtedad.setText(tbldatos.getValueAt(fila,3).toString());
            txtcorreo.setText(tbldatos.getValueAt(fila, 4).toString());
            btnañadir.setEnabled(false);
            btneliminar.setEnabled(false);
            
            
            
            
            
        }else{
            
            
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        if(fila != -1) {
            
            
            
            tbldatos.setValueAt(txtnombre.getText(), fila, 0);
            tbldatos.setValueAt(txtapellido.getText(), fila, 1);
            tbldatos.setValueAt(txtdireccion.getText(), fila, 2);
            tbldatos.setValueAt(txtedad.getText(), fila, 3);
            tbldatos.setValueAt(txtcorreo.getText(), fila, 4);
            fila = -1;
            limpiar();
            btnañadir.setEnabled(true);
            btneliminar.setEnabled(true);
            
            
        JOptionPane.showMessageDialog(null, "Se actualizo con exito");
        
            
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarActionPerformed
        respuesta respuesta = new respuesta();
        
        respuesta.setVisible(true);
        this.setVisible(false);
        respuestapersonas.atxtrecibirinfo.setText(persona.toString());
        
        tbldatos.setVisible(true);
        
        
        
    }//GEN-LAST:event_btnenviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablauno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablauno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablauno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablauno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tablauno().setVisible(true);
            }
        });
    }

    private void setLocationRelativeTo(int i, int i0) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnañadir;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnenviar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpndatos;
    private javax.swing.JPanel jpnprincipal;
    private javax.swing.JPanel jpntitulo;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lbledad;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTable tbldatos;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
